#pragma once

#include <map>
#include <string>

inline const std::map<std::string, std::string> &syntax_token_names() {
  static const std::map<std::string, std::string> names = {
    {"alignas", "KW_ALIGNAS"},
    {"alignof", "KW_ALIGNOF"},
    {"auto", "KW_AUTO"},
    {"bool", "KW_BOOL"},
    {"break", "KW_BREAK"},
    {"case", "KW_CASE"},
    {"catch", "KW_CATCH"},
    {"char", "KW_CHAR"},
    {"char16_t", "KW_CHAR16_T"},
    {"char32_t", "KW_CHAR32_T"},
    {"class", "KW_CLASS"},
    {"const", "KW_CONST"},
    {"constexpr", "KW_CONSTEXPR"},
    {"const_cast", "KW_CONST_CAST"},
    {"continue", "KW_CONTINUE"},
    {"decltype", "KW_DECLTYPE"},
    {"default", "KW_DEFAULT"},
    {"delete", "KW_DELETE"},
    {"do", "KW_DO"},
    {"double", "KW_DOUBLE"},
    {"dynamic_cast", "KW_DYNAMIC_CAST"},
    {"else", "KW_ELSE"},
    {"enum", "KW_ENUM"},
    {"explicit", "KW_EXPLICIT"},
    {"extern", "KW_EXTERN"},
    {"false", "KW_FALSE"},
    {"float", "KW_FLOAT"},
    {"for", "KW_FOR"},
    {"friend", "KW_FRIEND"},
    {"goto", "KW_GOTO"},
    {"if", "KW_IF"},
    {"inline", "KW_INLINE"},
    {"int", "KW_INT"},
    {"long", "KW_LONG"},
    {"mutable", "KW_MUTABLE"},
    {"namespace", "KW_NAMESPACE"},
    {"new", "KW_NEW"},
    {"noexcept", "KW_NOEXCEPT"},
    {"nullptr", "KW_NULLPTR"},
    {"operator", "KW_OPERATOR"},
    {"private", "KW_PRIVATE"},
    {"protected", "KW_PROTECTED"},
    {"public", "KW_PUBLIC"},
    {"register", "KW_REGISTER"},
    {"reinterpret_cast", "KW_REINTERPET_CAST"},
    {"return", "KW_RETURN"},
    {"short", "KW_SHORT"},
    {"signed", "KW_SIGNED"},
    {"sizeof", "KW_SIZEOF"},
    {"static", "KW_STATIC"},
    {"static_assert", "KW_STATIC_ASSERT"},
    {"static_cast", "KW_STATIC_CAST"},
    {"struct", "KW_STRUCT"},
    {"switch", "KW_SWITCH"},
    {"template", "KW_TEMPLATE"},
    {"this", "KW_THIS"},
    {"thread_local", "KW_THREAD_LOCAL"},
    {"throw", "KW_THROW"},
    {"true", "KW_TRUE"},
    {"try", "KW_TRY"},
    {"typedef", "KW_TYPEDEF"},
    {"typeid", "KW_TYPEID"},
    {"typename", "KW_TYPENAME"},
    {"union", "KW_UNION"},
    {"unsigned", "KW_UNSIGNED"},
    {"using", "KW_USING"},
    {"virtual", "KW_VIRTUAL"},
    {"void", "KW_VOID"},
    {"volatile", "KW_VOLATILE"},
    {"wchar_t", "KW_WCHAR_T"},
    {"while", "KW_WHILE"},
    {"{", "OP_LBRACE"},
    {"}", "OP_RBRACE"},
    {"[", "OP_LSQUARE"},
    {"]", "OP_RSQUARE"},
    {"(", "OP_LPAREN"},
    {")", "OP_RPAREN"},
    {"|", "OP_BOR"},
    {"^", "OP_XOR"},
    {"~", "OP_COMPL"},
    {"&", "OP_AMP"},
    {"!", "OP_LNOT"},
    {";", "OP_SEMICOLON"},
    {":", "OP_COLON"},
    {"...", "OP_DOTS"},
    {"?", "OP_QMARK"},
    {"::", "OP_COLON2"},
    {".", "OP_DOT"},
    {".*", "OP_DOTSTAR"},
    {"+", "OP_PLUS"},
    {"-", "OP_MINUS"},
    {"*", "OP_STAR"},
    {"/", "OP_DIV"},
    {"%", "OP_MOD"},
    {"=", "OP_ASS"},
    {"<", "OP_LT"},
    {">", "OP_GT"},
    {"+=", "OP_PLUSASS"},
    {"-=", "OP_MINUSASS"},
    {"*=", "OP_STARASS"},
    {"/=", "OP_DIVASS"},
    {"%=", "OP_MODASS"},
    {"^=", "OP_XORASS"},
    {"&=", "OP_BANDASS"},
    {"|=", "OP_BORASS"},
    {"<<=", "OP_LSHIFTASS"},
    {">>=", "OP_RSHIFTASS"},
    {"==", "OP_EQ"},
    {"!=", "OP_NE"},
    {"<=", "OP_LE"},
    {">=", "OP_GE"},
    {"&&", "OP_LAND"},
    {"||", "OP_LOR"},
    {"++", "OP_INC"},
    {"--", "OP_DEC"},
    {",", "OP_COMMA"},
    {"->*", "OP_ARROWSTAR"},
    {"->", "OP_ARROW"},
    {"<<", "OP_LSHIFT"},
    {">>", "OP_RSHIFT"}};;
  return names;
}

inline std::string syntax_token_label(const std::string &text) {
  const std::map<std::string, std::string> &names = syntax_token_names();
  const std::map<std::string, std::string>::const_iterator it = names.find(text);
  return it == names.end() ? "TT_IDENTIFIER:" + text : it->second + ":" + text;
}

inline bool syntax_is_keyword(const std::string &text) {
  const std::map<std::string, std::string> &names = syntax_token_names();
  const std::map<std::string, std::string>::const_iterator it = names.find(text);
  return it != names.end() && it->second.compare(0, 3, "KW_") == 0;
}

inline bool syntax_is_operator(const std::string &text) {
  const std::map<std::string, std::string> &names = syntax_token_names();
  const std::map<std::string, std::string>::const_iterator it = names.find(text);
  return it != names.end() && it->second.compare(0, 3, "OP_") == 0;
}
